apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  # capacity and storage is dummy in EFS, just for api definition
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "" # for static provisioning sc should be empty
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: efs:fs-0d9cbbf0f3d4d0906