apiVersion: v1
kind: Service
metadata:
  name: nginx
  # servicer labels
  labels:
    project: roboshop
    environment: dev
spec:
# service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: frontned
    component: frontned
  ports:
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    environment: dev
    component: frontned
    tier: frontned
spec:
  containers:
  - name: nginx # container
    image: nginx #by default it'll get gtom docker hub
    